import type { Metadata } from "next";
import "./globals.css";
import { robotoSlab } from '@/app/ui/fonts';
import TopNav from '@/app/ui/topnav'; // Importa el componente TopNav aquí

export const metadata: Metadata = {
  title: "Bookit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#F8F4E1] ${robotoSlab.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
