import type { Metadata } from "next";
import "./globals.css";
import { robotoSlab } from '@/app/ui/fonts';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSlab.className} antialiased`}>{children}</body>
    </html>
  );
}
